
package mx.ine.sif.soapws.adminusuarios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdminUsuariosEndpoint", targetNamespace = "http://www.ine.mx/au/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdminUsuariosEndpoint {


    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/crearUsuario")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta crearUsuario(
        @WebParam(name = "CrearUsuarioRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        CrearUsuarioRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/consultarUsuario")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta consultarUsuario(
        @WebParam(name = "ConsultarUsuarioRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        ConsultarUsuarioRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/consultarUsuario")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta consultarUsuarioPorCurp(
        @WebParam(name = "ConsultarUsuarioPorCurpRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        ConsultarUsuarioPorCurpRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/modificarUsuario")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta modificarUsuario(
        @WebParam(name = "ModificarUsuarioRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        ModificarUsuarioRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/cambiarPassword")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta cambiarPassword(
        @WebParam(name = "CambiarPasswordRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        CambiarPasswordRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/restablecerPassword")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta restablecerPassword(
        @WebParam(name = "RestablecerPasswordRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        RestablecerPasswordRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/agregarUsuariosAGrupo")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta agregarUsuariosAGrupo(
        @WebParam(name = "AgregarUsuariosAGrupoRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        OperacionGrupoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/eliminarUsuariosDeGrupo")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta eliminarUsuariosDeGrupo(
        @WebParam(name = "EliminarUsuariosDeGrupoRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        OperacionGrupoRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/eliminarUsuario")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta eliminarUsuario(
        @WebParam(name = "EliminarUsuarioRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        EliminarUsuarioRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.ine.sif.soapws.adminusuarios.Respuesta
     */
    @WebMethod(action = "http://www.ine.mx/au/ws/autenticarUsuario")
    @WebResult(name = "Respuesta", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
    public Respuesta autenticarUsuario(
        @WebParam(name = "AutenticarUsuarioRequest", targetNamespace = "http://www.ine.mx/au/ws", partName = "parameters")
        AutenticarUsuarioRequest parameters);

}
