
package mx.ine.sif.soapws.adminusuarios;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminUsuariosService", targetNamespace = "http://www.ine.mx/au/ws", wsdlLocation = "http://localhost:8080/aus/adminUsuariosService?wsdl")
public class AdminUsuariosService
    extends Service implements Serializable
{
  
    /**
	 * 
	 */
	private static final long serialVersionUID = -6264023766266834136L;
	private final static URL ADMINUSUARIOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINUSUARIOSSERVICE_EXCEPTION;
    private final static QName ADMINUSUARIOSSERVICE_QNAME = new QName("http://www.ine.mx/au/ws", "AdminUsuariosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/aus/adminUsuariosService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINUSUARIOSSERVICE_WSDL_LOCATION = url;
        ADMINUSUARIOSSERVICE_EXCEPTION = e;
    }

    public AdminUsuariosService() {
        super(__getWsdlLocation(), ADMINUSUARIOSSERVICE_QNAME);
    }

    public AdminUsuariosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINUSUARIOSSERVICE_QNAME, features);
    }

    public AdminUsuariosService(URL wsdlLocation) {
        super(wsdlLocation, ADMINUSUARIOSSERVICE_QNAME);
    }

    public AdminUsuariosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINUSUARIOSSERVICE_QNAME, features);
    }

    public AdminUsuariosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminUsuariosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdminUsuariosEndpoint
     */
    @WebEndpoint(name = "AdminUsuariosPort")
    public AdminUsuariosEndpoint getAdminUsuariosPort() {
        return super.getPort(new QName("http://www.ine.mx/au/ws", "AdminUsuariosPort"), AdminUsuariosEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminUsuariosEndpoint
     */
    @WebEndpoint(name = "AdminUsuariosPort")
    public AdminUsuariosEndpoint getAdminUsuariosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ine.mx/au/ws", "AdminUsuariosPort"), AdminUsuariosEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINUSUARIOSSERVICE_EXCEPTION!= null) {
            throw ADMINUSUARIOSSERVICE_EXCEPTION;
        }
        return ADMINUSUARIOSSERVICE_WSDL_LOCATION;
    }

}
